-- By penpem

DROP TABLE opravy;
DROP TABLE mechanik;
DROP TABLE auta;


CREATE TABLE mechanik
(
    cisloM  INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    meno    VARCHAR(255) NOT NULL
);


CREATE TABLE auta
(
    SPZ INT NOT NULL PRIMARY KEY,
    znacka VARCHAR(255) NOT NULL,
    r_vyroby INT NOT NULL
);

CREATE TABLE opravy
(
    cisloO  INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    cisloM  INT REFERENCES mechanik (cisloM),
    SPZ     INT REFERENCES auta (SPZ) NOT NULL,
    datum   DATE NOT NULL,
    cena    INT NOT NULL,
    typ     VARCHAR(255) NOT NULL
);

INSERT INTO auta VALUES (123, 'Ford', 2005);
INSERT INTO auta VALUES (999, 'Volvo', 2000);

INSERT INTO mechanik VALUES (69, 'Adam');
INSERT INTO mechanik VALUES (42, 'Betka');

INSERT INTO opravy (cisloM, SPZ, datum, cena, typ) VALUES (69, 123, TO_DATE('2022-03-28', 'YYYY-MM-DD'), 100000, 'vymena');
INSERT INTO opravy (cisloM, SPZ, datum, cena, typ) VALUES (42, 999, TO_DATE('2022-03-28', 'YYYY-MM-DD'), 25000, 'brzdy');
INSERT INTO opravy (cisloM, SPZ, datum, cena, typ) VALUES (42, 999, TO_DATE('2022-03-28', 'YYYY-MM-DD'), 50001, 'vymena');
INSERT INTO opravy (cisloM, SPZ, datum, cena, typ) VALUES (42, 999, TO_DATE('2022-03-28', 'YYYY-MM-DD'), 58000, 'vymena');
